<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IndustrialIoT.Protocols\IndustrialIoT.Protocols.csproj" />
    <ProjectReference Include="..\IndustrialIoT.Domain\IndustrialIoT.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentModbus" Version="5.3.2" />
    <PackageReference Include="HslCommunication" Version="12.6.4" />
    <PackageReference Include="System.IO.Ports" Version="8.0.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
